apiVersion: v1
kind: Pod
metadata:
  name: communicator-users-service
  labels:
    purpose: dev
    app: communicator-users-service

spec:
  containers:
    - name: communicator-users-service
      image: communicator-users-service
      ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: communicator-users-service
  labels:
    app: communicator-users-service
    service: communicator-users-service
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: communicator-users-service
