---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: communicator-dev
  name: users
  labels:
    account: users

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: communicator-dev
  name: users
  labels:
    purpose: dev
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users

  template:
    metadata:
      labels:
        app: users

    spec:
      serviceAccountName: users
      containers:
        - name: users
          image: users
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            #app
            - name: ENV
              value: local
            - name: PORT
              value: "4000"
            #postgres
            - name: POSTGRES_HOST
              value: users-db-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_DATABASE
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-postgresql
                  key: postgres-password
            # rabbitmq
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password

---
apiVersion: v1
kind: Service
metadata:
  namespace: communicator-dev
  name: users
  labels:
    app: users
    service: users
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: users

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-ingress
  namespace: communicator-dev
  annotations:
    konghq.com/plugins: jwt,communicator-dev-cors
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "false"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /users
            pathType: ImplementationSpecific
            backend:
              service:
                name: users
                port:
                  number: 4000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: communicator-dev
  name: users
spec:
  hosts:
    - users
  http:
    - route:
        - destination:
            host: users
      # retries:
      #   attempts: 3
      #   perTryTimeout: 2s
      #   retryOn: connect-failure,refused-stream,503
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  namespace: communicator-dev
  name: users
spec:
  host: users
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-path-from-outside
  namespace: communicator-dev
spec:
  selector:
    matchLabels:
      app: users
  action: DENY
  rules:
    - from:
        - source:
            notPrincipals:
              - "cluster.local/ns/communicator-dev/sa/auth-hooks"
      to:
        - operation:
            paths: ["/users/create/account"]

    - from:
        - source:
            notPrincipals:
              - "cluster.local/ns/communicator-dev/sa/servers"
              - "cluster.local/ns/communicator-dev/sa/channels"
      to:
        - operation:
            paths: ["/users/data/*"]
