apiVersion: skaffold/v2beta28
kind: Config
build:
  local:
    concurrency: 1
    push: false
  artifacts:
    - image: users
      docker:
        dockerfile: Dockerfile.dev
manifests:
  rawYaml:
    - "./dev-k8s.yml"
