apiVersion: skaffold/v2beta28
kind: Config
build:
  local:
    concurrency: 0
    push: false
  artifacts:
    - image: users
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**.*.ts"
deploy:
  kubectl:
    manifests:
      - "./dev-k8s.yml"
