version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: communicator
          account-url: $AWS_ECR_ACCOUNT_URL
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./
          region: eu-central-1
          repo: communicator-container-repository
          skip-when-tags-exist: false
          tag: 'latest'