apiVersion: v1
kind: Service
metadata:
  name: communicator-users-service
  namespace: communicator-dev
spec:
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: communicator-users
    namespace: communicator-dev