apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: communicator-users-service
spec:
  hosts:
    - communicator-users-service
  http:
    - route:
        - destination:
            host: communicator-users-service
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: connect-failure,refused-stream,503
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: communicator-users-service
spec:
  host: communicator-users-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-path-from-outside
  namespace: communicator-dev
spec:
  selector:
    matchLabels:
      app: communicator-users-service
  action: DENY
  rules:
    - from:
        - source:
            notPrincipals:
              - "cluster.local/ns/communicator-dev/sa/communicator-auth-hooks-service"
      to:
        - operation:
            paths: ["/users/create/account"]
