apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app: users
    service: users
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: users
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: users
  labels:
    account: users
