apiVersion: v1
kind: Service
metadata:
  name: communicator-users-service
  labels:
    app: communicator-users-service
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: communicator-users-service
