apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: users
spec:
  hosts:
    - users
  http:
    - route:
        - destination:
            host: users
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: connect-failure,refused-stream,503
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: users
spec:
  host: users
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-path-from-outside
spec:
  selector:
    matchLabels:
      app: users
  action: DENY
  rules:
    - from:
        - source:
            notPrincipals:
              - "cluster.local/ns/communicator-dev/sa/auth-hooks"
      to:
        - operation:
            paths: ["/users/create/account"]

    - from:
        - source:
            notPrincipals:
              - "cluster.local/ns/communicator-dev/sa/servers"
              - "cluster.local/ns/communicator-dev/sa/channels"
      to:
        - operation:
            paths: ["/users/data/*"]
