name: Build and Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  DEPLOYMENT_NAME: users
  IMAGE: communicator_users
  REPOSITORY: ${{ secrets.REPOSITORY }}
  ENVIRONMENT: dev
  NAMESPACE: communicator-dev
  KUBECONFIG: /home/deploy/config

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js for tests
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - run: npm ci
      # - run: npm run test:cov

      - name: Create kubeconfig directory
        run: sudo mkdir -p /home/deploy

      # auth kubernetes cluster
      - name: Auth with Kubernetes cluster
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $KUBECONFIG

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "$REPOSITORY/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Push the Docker image to Dockerhub
      - name: Publish
        run: |-
          docker push "$REPOSITORY/$IMAGE:$GITHUB_SHA"

      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Deploy the Docker image to the cluster
      - name: Deploy
        run: |-
          (cd .github/workflows/base && ../../../kustomize edit set image communicator=$REPOSITORY/$IMAGE:$GITHUB_SHA)
          ./kustomize build .github/workflows/overlays/$ENVIRONMENT | kubectl apply -n $NAMESPACE -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE
          kubectl get services -o wide -n $NAMESPACE
