apiVersion: apps/v1
kind: Deployment
metadata:
  name: communicator-users
spec:
  selector:
    matchLabels:
      app: communicator-users
  template:
    metadata:
      labels:
        app: communicator-users
    spec:
      imagePullSecrets:
        - name: communicator-registry-key
      containers:
      - name: communicator-users
        image: rg.pl-waw.scw.cloud/communicator/communicator_users-service:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: communicator-users-service
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: communicator-users