name: Build Docker image and publish to the repository

env:
  IMAGE_NAME: communicator_users-service
  REPO_URL: rg.pl-waw.scw.cloud/communicator
  SCALEWAY_SECRET_TOKEN: ${{ secrets.SCALEWAY_SECRET_TOKEN }}

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get app version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: Login to the Docker repository
      run: docker login $REPO_URL -u nologin -p $SCALEWAY_SECRET_TOKEN
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest --tag $IMAGE_NAME:${{ steps.package-version.outputs.current-version }}
    - name: Push image to the repository
      run: docker push $IMAGE_NAME --all-tags
